# Generated by Django 6.0.3 on 2026-03-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Taom',
        ),
    ]
